version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: metaverse_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metaverse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
